export function convertNavigatoLang(lang: string): string {
    switch (lang) {
        case 'af':
            return 'af-ZA'
        case 'sq':
            return 'sq-AL'
        case 'ar-sa':
            return 'ar-SA'
        case 'ar-iq':
            return 'ar-IQ'
        case 'ar-eg':
            return 'ar-EG'
        case 'ar-ly':
            return 'ar-LY'
        case 'ar-dz':
            return 'ar-DZ'
        case 'ar-ma':
            return 'ar-MA'
        case 'ar-tn':
            return 'ar-TN'
        case 'ar-om':
            return 'ar-OM'
        case 'ar-ye':
            return 'ar-YE'
        case 'ar-sy':
            return 'ar-SY'
        case 'ar-jo':
            return 'ar-JO'
        case 'ar-lb':
            return 'ar-LB'
        case 'ar-kw':
            return 'ar-KW'
        case 'ar-ae':
            return 'ar-AE'
        case 'ar-bh':
            return 'ar-BH'
        case 'ar-qa':
            return 'ar-QA'
        case 'eu':
            return 'eu-ES'
        case 'bg':
            return 'bg-BG'
        case 'be':
            return 'be-BY'
        case 'ca':
            return 'ca-ES'
        case 'zh-tw':
            return 'zh-TW'
        case 'zh-cn':
            return 'zh-CN'
        case 'zh-hk':
            return 'zh-HK'
        case 'zh-sg':
            return 'zh-SG'
        case 'hr':
            return 'hr-HR'
        case 'cs':
            return 'cs-CZ'
        case 'da':
            return 'da-DK'
        case 'nl':
            return 'nl-NL'
        case 'nl-be':
            return 'nl-BE'
        case 'en':
            return 'en-US'
        case 'en-us':
            return 'en-US'
        case 'en-gb':
            return 'en-GB'
        case 'en-au':
            return 'en-AU'
        case 'en-ca':
            return 'en-CA'
        case 'en-nz':
            return 'en-NZ'
        case 'en-ie':
            return 'en-IE'
        case 'en-za':
            return 'en-ZA'
        case 'en-jm':
            return 'en-JM'
        case 'en-bz':
            return 'en-BZ'
        case 'en-tt':
            return 'en-TT'
        case 'et':
            return 'et-EE'
        case 'fo':
            return 'fo-FO'
        case 'fa':
            return 'fa-IR'
        case 'fi':
            return 'fi-FI'
        case 'fr':
            return 'fr-FR'
        case 'fr-be':
            return 'fr-BE'
        case 'fr-ca':
            return 'fr-CA'
        case 'fr-ch':
            return 'fr-CH'
        case 'fr-lu':
            return 'fr-LU'
        case 'gd':
            return 'gd-GB'
        case 'gd-ie':
            return 'gd-IE'
        case 'de':
            return 'de-DE'
        case 'de-ch':
            return 'de-CH'
        case 'de-at':
            return 'de-AT'
        case 'de-lu':
            return 'de-LU'
        case 'de-li':
            return 'de-LI'
        case 'el':
            return 'el-GR'
        case 'he':
            return 'he-IL'
        case 'hi':
            return 'hi-IN'
        case 'hu':
            return 'hu-HU'
        case 'is':
            return 'is-IS'
        case 'id':
            return 'id-ID'
        case 'it':
            return 'it-IT'
        case 'it-ch':
            return 'it-CH'
        case 'ja':
            return 'ja-JP'
        case 'ko':
            return 'ko-KR'
        case 'lv':
            return 'lv-LV'
        case 'lt':
            return 'lt-LT'
        case 'mk':
            return 'mk-MK'
        case 'mt':
            return 'mt-MT'
        case 'no':
            return 'no-NO'
        case 'pl':
            return 'pl-PL'
        case 'pt-br':
            return 'pt-BR'
        case 'pt':
            return 'pt-PT'
        case 'rm':
            return 'rm-CH'
        case 'ro':
            return 'ro-RO'
        case 'ro-mo':
            return 'ro-MO'
        case 'ru':
            return 'ru-RU'
        case 'ru-mo':
            return 'ru-RU'
        case 'sz':
            return 'sz-CH'
        case 'sr':
            return 'sr-RS'
        case 'sk':
            return 'sk-SK'
        case 'sl':
            return 'sl-SI'
        case 'sb':
            return 'sb-ZA'
        case 'es':
            return 'es-ES'
        case 'es-ar':
            return 'es-AR'
        case 'es-gt':
            return 'es-GT'
        case 'es-cr':
            return 'es-CR'
        case 'es-pa':
            return 'es-PA'
        case 'es-do':
            return 'es-DO'
        case 'es-mx':
            return 'es-MX'
        case 'es-ve':
            return 'es-VE'
        case 'es-co':
            return 'es-CO'
        case 'es-pe':
            return 'es-PE'
        case 'es-ec':
            return 'es-EC'
        case 'es-cl':
            return 'es-CL'
        case 'es-uy':
            return 'es-UY'
        case 'es-py':
            return 'es-PY'
        case 'es-bo':
            return 'es-BO'
        case 'es-sv':
            return 'es-SV'
        case 'es-hn':
            return 'es-HN'
        case 'es-ni':
            return 'es-NI'
        case 'es-pr':
            return 'es-PR'
        case 'sx':
            return 'sx-SX'
        case 'sv':
            return 'sv-SV'
        case 'sv-fi':
            return 'sv-FI'
        case 'th':
            return 'th-TH'
        case 'ts':
            return 'ts-ZA'
        case 'tn':
            return 'tn-ZA'
        case 'tr':
            return 'tr-TR'
        case 'uk':
            return 'uk-UA'
        case 'ur':
            return 'ur-PK'
        case 've':
            return 've-VE'
        case 'vi':
            return 'vi-VN'
        case 'xh':
            return 'xh-ZA'
        case 'ji':
            return 'ji-IL'
        case 'zu':
            return 'zu-ZA'
        default:
            return 'en-US'
    }
}
